###
GET https://www.pajarito.site/api/guest


###
POST https://www.pajarito.site/api/guest
content-type: application/json

{
    "Name": "MIOdfd",
    "LastName": "TU"
}

###
PUT  http://localhost:3000/api/guest
content-type: application/json

{
    "Name": "Sanel",
    "LastName": "Meza",
    "GuestID": "3"
}

###
DELETE   http://localhost:3000/api/guest
content-type: application/json

{
    "GuestID": "4"
}