###
GET https://www.pajarito.site/api/taskRead?guestId=

###
POST https://www.pajarito.site/api/taskCreate
content-type: application/json

{
    "taskName": "tiende la ropa",
    "description": "holadsfaf",
    "guestID": "19"
}

###
PUT  https://www.pajarito.site/api/taskUpdate
content-type: application/json

{
    "taskName": "Get it",
    "description": "a las minutes",
    "taskID": "5"
}

###
DELETE   http://localhost:3000/api/taskDelete
content-type: application/json

{
    "taskID": "4"
}