name: CI Pipeline

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v5

      # 2. Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Lint
      - name: Run ESLint
        run: npm run lint

      # 5. Test
      - name: Run tests
        run: npm test


  deploy:
    needs: ci
    if: github.event_name == 'push' && contains(github.event.head_commit.message, '[CICD]')
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            export PATH="/home/christiangaspar55/.nvm/versions/node/v24.14.0/bin:$PATH"
            cd /home/christiangaspar55/taskFlowBackend
            git fetch origin
            git reset --hard origin/master
            npm ci --omit=dev
            pm2 restart controller